const express = require("express");
const router = express.Router();
const ctrl = require("../controllers/pedidoController");
router.get("/stats", ctrl.obterStats);
router.get("/", ctrl.listarPedidos);
router.get("/:id", ctrl.obterPedido);
router.post("/", ctrl.criarPedido);
router.put("/:id", ctrl.atualizarPedido);
router.delete("/:id", ctrl.excluirPedido);
module.exports = router;